spring:
  application:
    name: basic-security

  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

acm:
  web:
    json:
      snake-case: true
    tracing:
      enable: true
    request-logging:
      enabled: true
      max-body-size: 4096
      excluded-paths:
        - /actuator/**
        - /health
        - /ws/**

      masking:
        sensitive-fields:
          - token
          - authorization
          - national_id
        mask-pattern: "***MASK FOR SECURITY***"
        partial-unmask-chars: 4

  datasource:
    master:
      host: localhost
      port: 5432
      database: spring_security
      username: postgres
      password: Kimla110803
    flyway:
      enabled: true
      locations:
        - classpath:db.migration

  observability:
    enabled: true
    service-name: spring-security

    health:
      enabled: true