spring:
  application:
    name: krob-krong
  threads:
    virtual:
      enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/krob_krong
    username: postgres
    password: supersecret
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: KrobKrongHikariPool
      maximum-pool-size: 20
      minimum-idle: 20
      connection-timeout: 30000 # 30 seconds
      idle-timeout: 600000       # 10 minutes
      max-lifetime: 1800000      # 30 minutes
      keepalive-time: 60000      # 1 minute
      leak-detection-threshold: 2000 # 2 seconds (DEV/TEST recommended)
  flyway:
    enabled: true
    locations: db/migration
    table: flyway_schema_history

mask:
  sensitive-fields:
    - token
    - authorization
    - national_id
  mask-pattern: "***MASK FOR SECURITY***"
  partial-unmask-chars: 4